feat: xp command strings
ProBotOrg/locale pull request #371
Opened 2022-09-16 08:10 UTC by FnrDev

**Please describe the changes this PR makes and why it should be merged:**

**In this PR:**

2022-09-17 05:23 UTC, Dramex commented on en/bot.json
> +	"xp_description": "Add / remove xp from a user.",
```suggestion
	"setxp_description": "Add / remove xp from a user.",
```

2022-09-17 05:24 UTC, Dramex commented on en/website.json
> +    "xp_description": "Add / remove xp from a user."
```suggestion
    "setxp_description": "Changes member xp."
```

2022-09-17 05:25 UTC, Dramex requested changes
fixes

2022-09-19 12:07 UTC, Anasqx requested changes

2022-09-19 12:07 UTC, Anasqx commented on en/bot.json
>  	"setxp_text_select": "Adds xp in text",
Adds xp to the text level

2022-09-19 12:23 UTC, Anasqx requested changes

2022-09-19 12:23 UTC, Anasqx commented on en/bot.json
> +	"setxp_add_user_description": "The user you want to add xp to.",
The user to whom you want to add xp.

2022-09-19 12:23 UTC, Anasqx commented on en/bot.json
> +	"setxp_add_xp_description": "The number of xp to add to the user.",
The amount of xp to add to the user.

2022-09-19 12:23 UTC, Anasqx commented on en/bot.json
> +	"setxp_remove_xp_description": "The number of removing xp from the user.",
The amount of xp you want to remove from the user

2022-09-19 12:23 UTC, Anasqx commented on en/bot.json
> +	"setxp_remove_user_description": "The user you want to remove xp from",
The user from whom you want to remove xp.

2022-09-19 12:23 UTC, Anasqx commented on en/bot.json
> +	"setxp_changed_xp": "**✅ Changed xp for @{0}**",
**☑️ | XP has been updated for @{0}**"

2022-09-19 12:23 UTC, Anasqx commented on en/bot.json
> +	"setxp_select_type": "**Please select type of xp.**",
Please select the xp type.

2022-09-26 11:07 UTC, merged